Employees.Web/Models/Employee/EmployeeCreateModel.cs
using System.Collections.Generic;
using Employees.Models;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Employees.Web.Models.Department;
using Employees.Web.Models.ProgrammingLanguage;

namespace Employees.Web.Models.Employee
{
    public class EmployeeCreateModel
    {
        [DisplayName("Имя")]
        [Required]
        public string FirstName { get; set; }
        
        [DisplayName("Фамилия")]
        [Required]
        public string LastName { get; set; }
        
        [DisplayName("Возраст")]
        [Range(1, 128)]
        public int Age { get; set; }
        
        [DisplayName("Пол")]
        public Sex Sex { get; set; }

        [DisplayName("Отдел")]
        [Required]
        public int DepartmentId { get; set; }

        public ICollection<DepartmentSelectModel> Departments { get; set; }

        [DisplayName("Язык программирования")]
        [Required]
        public int ProgrammingLanguageId { get; set; }

        public ICollection<ProgrammingLanguageSelectModel> ProgrammingLanguages { get; set; }
    }
}

Employees.Web/Models/Employee/EmployeeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Employees.Web.Models.Employee
{
    public class EmployeeModel
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public string Department { get; set; }
        public string ProgrammingLanguage { get; set; }
    }
}

Employees.Web/Models/Employee/EmployeeUpdateModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Employees.Models;
using System.ComponentModel.DataAnnotations;

namespace Employees.Web.Models.Employee
{
    public class EmployeeUpdateModel : EmployeeCreateModel
    {
        [Required]
        public int Id { get; set; }
    }
}

Employees.Web/Controllers/EmployeeController.cs
namespace Employees.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using AutoMapper;
    using Employees.Models;
    using Employees.Data;
    using Employees.Web.Models.Employee;
    using Employees.Web.Models.Department;
    using Employees.Web.Models.ProgrammingLanguage;
    using Employees.Data.EF;

    public class EmployeeController : Controller
    {
        IUnitOfWork _uow;

        public EmployeeController()
        {
            // it is good idea to use dependency injection here
            _uow = new EFUnitOfWork();
        }

        public ActionResult Index()
        {
            var employees = _uow.Employees
                .AllIncluding(e => e.Department, e => e.ProgrammingLanguage)
                .OrderBy(e => e.Id)
                .ToArray();
            var model = employees.Select(Mapper.Map<EmployeeModel>).ToArray();

            return View(model);
        }

        public ActionResult Create()
        {
            var model = new EmployeeCreateModel();
            SetDepartmentsAndProgrammingLanguages(model);
            // initialization of a new employee with the default values
            model.Age = 18;
            model.Sex = Sex.Male;

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create(EmployeeCreateModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var employee = Mapper.Map<Employee>(model);
            _uow.Employees.Create(employee);
            _uow.Save();

            return RedirectToAction("Index");
        }

        public ActionResult Update(int id)
        {
            if (id <= 0)
            {
                return new HttpNotFoundResult();
            }

            var employee = _uow.Employees.Read(id);
            var model = Mapper.Map<EmployeeUpdateModel>(employee);
            SetDepartmentsAndProgrammingLanguages(model);

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Update(EmployeeUpdateModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var employee = Mapper.Map<Employee>(model);
            _uow.Employees.Update(employee);
            _uow.Save();

            return RedirectToAction("Index");
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            if (id <= 0) 
            {
                return HttpNotFound();
            }

            _uow.Employees.Delete(id);
            _uow.Save();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult GetAutocompleteNames(string query)
        {
            if (String.IsNullOrEmpty(query))
            {
                return new JsonResult();
            }

            var employees = _uow.Employees
                .All()
                .Select(e => e.FirstName)
                .Distinct()
                .Where(e => e.Contains(query))
                .Take(10)
                .ToArray();

            return Json(employees);
        }

        private void SetDepartmentsAndProgrammingLanguages(EmployeeCreateModel model)
        {
            var departments = _uow.Departments.All().ToArray() ;
            var departmentsModels = departments.Select(Mapper.Map<DepartmentSelectModel>).ToArray();
            var programmingLanguages = _uow.ProgrammingLanguages.All().ToArray();
            var programmingLanguagesModels = programmingLanguages.Select(Mapper.Map<ProgrammingLanguageSelectModel>).ToArray();

            model.Departments = departmentsModels;
            model.ProgrammingLanguages = programmingLanguagesModels;
        }

        private bool _disposed;
        protected override void Dispose(bool disposing)
        {
            if (!_disposed)
            {
                if (disposing)
                {
                    if (_uow != null) 
                    { 
                        _uow.Dispose(); 
                    } 

                    base.Dispose(disposing);

                    _disposed = true;
                }
            }
        }
    }
}

Employees.Web/Views/Employee/Create.cshtml
@model Employees.Web.Models.Employee.EmployeeCreateModel

@{
    ViewBag.Title = "Добавление сотрудника";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()
    <fieldset>
        <h2>@ViewBag.Title</h2>
        @*<legend>EmployeeCreateModel</legend>*@

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.FirstName, new { id = "firstName" })
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Age)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Age)
            @Html.ValidationMessageFor(model => model.Age)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DepartmentId)
        </div>
        <div class="editor-field">
            @{
                var departmentSelectList = Model
                    .Departments
                    .Select(pl => new SelectListItem { Text = pl.Name, Value = pl.Id.ToString() })
                    .ToList();
                    
                departmentSelectList.Insert(0, new SelectListItem());;
            }
            @Html.DropDownListFor(model => model.DepartmentId, 
                departmentSelectList,
                new { @class = "inputWidth", data_placeholder = "Выберите отдел" })
            @Html.ValidationMessageFor(model => model.DepartmentId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProgrammingLanguageId)
        </div>
        <div class="editor-field">
            @{
                var programmingLanguageSelectList = Model
                    .ProgrammingLanguages
                    .Select(pl => new SelectListItem { Text = pl.Name, Value = pl.Id.ToString() })
                    .ToList();
                    
                programmingLanguageSelectList.Insert(0, new SelectListItem());;
            }
            @Html.DropDownListFor(model => model.ProgrammingLanguageId, 
                programmingLanguageSelectList,
             new { @class = "inputWidth", data_placeholder = "Выберите язык" })           
            @Html.ValidationMessageFor(model => model.ProgrammingLanguageId)
        </div>

        <p>
            <input type="submit" value="Добавить" />
            @Html.ActionLink("Отмена", "Index")
        </p>
    </fieldset>
}
<script src="@Url.Content("~/Scripts/chosen.jquery.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Project/EmployeeCreateUpdate.js")" type="text/javascript"></script>

Employees.Web/Views/Employee/Index.cshtml
@using Employees.Web.Models.Employee;
@model ICollection<Employees.Web.Models.Employee.EmployeeModel>

@{
    ViewBag.Title = "Список сотрудников";
}

<h2>@ViewBag.Title</h2>
@Html.ActionLink("Добавить", "Create")
<p />
<table>
    <tr>
        <th>Имя</th>
        <th>Фамилия</th>
        <th>Возраст</th>
        <th>Отдел</th>
        <th>Язык</th>
    </tr>
@foreach (var employee in Model)
{
    <tr>        
        <td>@employee.FirstName</td>
        <td>@employee.LastName</td>
        <td>@employee.Age</td>
        <td>@employee.Department</td>
        <td>@employee.ProgrammingLanguage</td>
        <td>
            @Html.ActionLink("Изменить", "Update", new { id = employee.Id })
            <a class="deleteEmployeeLink" href="#" data-id="@employee.Id">Удалить</a>
            @**@
        </td>
    </tr>
}
</table>
@using (var form = Html.BeginForm("Delete", "Employee", FormMethod.Post, new { id = "deleteEmployeeForm" }))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("id", 0, new { id = "deleteEmployeeId" })
}
<script src="@Url.Content("~/Scripts/Project/EmployeeDelete.js")" type="text/javascript"></script>

Employees.Web/Views/Employee/Update.cshtml
@model Employees.Web.Models.Employee.EmployeeUpdateModel

@{
    ViewBag.Title = "Изменение данных о сотруднике";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <h2>@ViewBag.Title</h2>
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.FirstName, new { id = "firstName" })
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Age)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Age)
            @Html.ValidationMessageFor(model => model.Age)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DepartmentId)
        </div>
        <div class="editor-field">
            @{
                var departmentSelectList = Model
                    .Departments
                    .Select(pl => new SelectListItem { Text = pl.Name, Value = pl.Id.ToString() })
                    .ToList();
                    
                departmentSelectList.Insert(0, new SelectListItem());;
            }
            @Html.DropDownListFor(model => model.DepartmentId, 
                departmentSelectList,
                new { @class = "inputWidth", data_placeholder = "Выберите отдел" })
            @Html.ValidationMessageFor(model => model.DepartmentId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProgrammingLanguageId)
        </div>
        <div class="editor-field">
            @{
                var programmingLanguageSelectList = Model
                    .ProgrammingLanguages
                    .Select(pl => new SelectListItem { Text = pl.Name, Value = pl.Id.ToString() })
                    .ToList();
                    
                programmingLanguageSelectList.Insert(0, new SelectListItem());;
            }
            @Html.DropDownListFor(model => model.ProgrammingLanguageId, 
                programmingLanguageSelectList,
             new { @class = "inputWidth", data_placeholder = "Выберите язык" })           
            @Html.ValidationMessageFor(model => model.ProgrammingLanguageId)
        </div>

        <p>
            <input type="submit" value="Сохранить" />
            @Html.ActionLink("Отмена", "Index")
        </p>
    </fieldset>
}
<script src="@Url.Content("~/Scripts/chosen.jquery.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Project/EmployeeCreateUpdate.js")" type="text/javascript"></script>